### ISSUE TITLE
fpga commands on MCU not working in rev 2

### ISSUE THREAD

**Issue by pwittich** [apollo-lhc/cm_mcu#117]
**Describe the bug**
`fpga done` does not appear to show the correct state of the done bit
`reset_fpga k` does not reset f1 as expected.

**Comment by pwittich** [comment]
CRS says FPGA_DONE is bad due to Rev2 hardware issue

**Comment by pwittich** [comment]
@pkotamnives @rzouCERN can one of you reset a Rev1 fpga next time you've programmed one and confirm it works?

**Comment by pkotamnives** [comment]
@pwittich do you mean that just `reboot` the zynq and check if after programming the fpgas they are all detectable by `status 3 FIRMWARE`?  I can check that now if so.

**Comment by pwittich** [comment]
no, I mean checking `status 3 FIRMWARE` before and after doing `reset_fpga k` or `reset_fpga v` on the microcontroller command line. I think you can do that form BUTool via `uart_cmd CM_1 reset_fpga k`

**Comment by pwittich** [comment]
@pkotamnives confirms this works on Rev1.

**Comment by pwittich** [comment]
still doesn't appear to work
