### ISSUE TITLE
Update I2C programming interface to allow for the new larger EEPROM on Rev2b

### ISSUE THREAD

**Issue by pwittich** [apollo-lhc/cm_mcu#123]
Rev2b will have a larger EEPROM where the address is more than one byte. Need to adapt to this.

First pass might be to just change the commands here to allow for multi-byte addresses
https://github.com/apollo-lhc/cm_mcu/blob/4479f34eda6a9a73dfcfe26c54713109c439215f/projects/cm_mcu/I2CCommunication.c#L110

that is, 
1. change `reg_address` from a uint8_t to an array (like the `data` field)
2. add an argument `nbytes_addr` similar to the `nbytes` field which counts how many address bytes there are
3. change the code here to adapt to this https://github.com/apollo-lhc/cm_mcu/blob/4479f34eda6a9a73dfcfe26c54713109c439215f/projects/cm_mcu/I2CCommunication.c#L129-L132
   both the read and write reg functions will need to be adapted. I think 4 bytes of address is probably enough.
4. adapt the CLI functions in https://github.com/apollo-lhc/cm_mcu/blob/4479f34eda6a9a73dfcfe26c54713109c439215f/projects/cm_mcu/commands/I2CCommands.c#L30 for the new interface. Probably will not need to change the parsing of the input, just the backend
5. adapt all other places where the relevant functions are used.

Data sheet for new EEPROM attached to this issue.

[24CS512_EEPROM.pdf](https://github.com/apollo-lhc/cm_mcu/files/8089496/24CS512_EEPROM.pdf)

There is a board with such an EEPROM available somewhere, @CRStrohman  can tell us.
 
Detailed prescription from CRS:

> I've attached the datasheet, and here is a quick summary of writing one 
byte to a random address or reading one byte from a random address. I 
don't think we can generate these sequences with the current commands. 
There are also "page write" (page 16), "current address read" (page 20), 
and "sequential read" (page 22).

> Write one random byte (page 15):
> 1) send START
> 2) send device address byte
> 3) wait for ACK
> 4) send high address byte
> 5) wait for ACK
> 6) send low address byte
> 7) wait for ACK
> 8) send data byte
> 9) wait for ACK
> 10) send STOP
> 11) EEPROM is unavailable for Twc (5 msec max)
> 
> 
> Read one random byte (page 21):
> 1) send START
> 2) send device address byte
> 3) wait for ACK
> 4) send high address byte
> 5) wait for ACK
> 6) send low address byte
> 7) wait for ACK
> 8) send RESTART
> 9) send device address
> 10) wait for ACK
> 11) read data byte
> 12) send NACK (I think the picture on page 21 is wrong at this point)
> 13) send STOP
> 
> We will probably want "page write" and "sequential read" for storing and 
> reading clock chip configuration data. The "page write" will probably 
> want a command-line function that is driven from the Zynq. The 5 msec 
> write cycle is incurred for either a single byte or an entire 128 byte 
> page. I don't think we need a command-line function for "sequential read".
>

**Comment by pkotamnives** [comment]
Update on 02/25/22: we decide to do the following instead:
- Change int to uint32_t for the packed_data
- Make the reg_w and reg_r function the same (ie. both use the packed_data)
- No using of pointers or arrays for reg_address, modify it as `uint16_t packed_address`
