### ISSUE TITLE
detect first-time setup of MCU and prompt loading of internal EEPROM configuration

### ISSUE THREAD

**Issue by pwittich** [apollo-lhc/cm_mcu#139]
We should detect the first-time loading of the MCU and prompt the loading of the relevant information via the CLI.
I think what needs to be set are

- revision number
- board id number
- firefly mask
- PS ignore mask (hopefully 0)

**Comment by pkotamnives** [comment]
@pwittich , should we also add a new flag (e.g. NEW=1 for a new board which I assume first-time setup of MCU ) that Charlie suggested to skip clock loading, and monitoring those I2C devices if there are not enabled?
