### ISSUE TITLE
Delay semaphore not taken in MONI2C and MON 

### ISSUE THREAD

**Issue by pkotamnives** [apollo-lhc/cm_mcu#190]
**Is your feature request related to a problem? Please describe.**
the way monitoring task i.e. MONI2C and MON handles semaphore not being taken on time is different. 

**Describe the solution you'd like**
We may need to think about the best way to delay it so the next iteration in the loop can continue. 

**Additional context**
The issue was initially discussed in https://github.com/apollo-lhc/cm_mcu/pull/189#discussion_r1243704130

**Comment by pwittich** [comment]
I think this was taken care of in the interim.
https://github.com/apollo-lhc/cm_mcu/blob/9210313d2bb8c62da97e5f0eae4c340bd89ecffb/projects/cm_mcu/MonitorTaskI2C.c#L57-L63
