### ISSUE TITLE
ff xmit on all takes minutes to finish with warnings about clock monitor task

### ISSUE THREAD

**Issue by rzouCERN** [apollo-lhc/cm_mcu#192]
Issue described as in title. See log below.

Firmware version used: 
% version
Version commit date 2023-02-20 16:32:52 -0500   (grafted, HEAD, tag: v0.99.2) v0.99.2
regular build
 built at 17:35:47, Feb 24 2023.

% ff xmit on all
2051347743 SRV WRN MonitorI2CTask.c:89:CLKSI could not get semaphore in time; continue
2051347744 SRV WRN MonitorI2CTask.c:89:CLKR0A could not get semaphore in time; continue
2051349792 SRV WRN SensorControl.c:106:could not get semaphore in time
2051352753 SRV WRN MonitorI2CTask.c:89:CLKSI could not get semaphore in time; continue
2051352754 SRV WRN MonitorI2CTask.c:89:CLKR0A could not get semaphore in time; continue
2051367784 SRV WRN MonitorI2CTask.c:89:CLKR0A could not get semaphore in time; continue

2051368209 SRV WRN SensorControl.c:124:write_ff_register: FF writing error 5 (ADDR_ACK_ERROR) (ff=F1_2  12 Tx) ...
2051368211 SRV WRN SensorControl.c:124:write_ff_register: FF writing error 5 (ADDR_ACK_ERROR) (ff=F1_4 4 XCVR) ...
2051368309 SRV WRN SensorControl.c:124:write_ff_register: FF writing error 5 (ADDR_ACK_ERROR) (ff=F2_2  12 Tx) ...
2051368311 SRV WRN SensorControl.c:124:write_ff_register: FF writing error 5 (ADDR_ACK_ERROR) (ff=F2_4 4 XCVR) ...

**Comment by pwittich** [comment]
The first set of errors about the CLK* are ignorable; the second set of errors (ADDR_ACK_ERROR) are bad and should not happen if the PRESENT mask is working. Does the error set continue like this forever?

**Comment by pkotamnives** [comment]
@pwittich , we have tried this command with the latest FW in the master branch (v0.99.4) and there was no warning or error.

**Comment by pwittich** [comment]
so does that mean we can close this issue?

**Comment by pwittich** [comment]
This is no longer active so I am closing it. Please reopen if this is wrong.
