### ISSUE TITLE
Upgrade packer to new version 2 to allow MCU to send more FF data on UART Push link 

### ISSUE THREAD

**Issue by pkotamnives** [apollo-lhc/cm_mcu#197]
We currently send an average value of optical power from all channels of each FF device. With a new auto-encoder, we will send optical power per channel. 

Additionally, Rui requested us to send outputs from transmit output disable register as well. 

**Describe the solution you'd like**
Follow a new auto-encoder as in [here](https://gitlab.com/apollo-lhc/FW/SM_ZYNQ_FW/-/blob/develop/src/CM_interface/CM_Monitoring/data_format.md?ref_type=heads) and modify [this function](https://github.com/apollo-lhc/cm_mcu/blob/master/projects/cm_mcu/ZynqMonTask.c#L54). 

Then, just add more zynqmon data steams as we have done before.

**Comment by pwittich** [comment]
changed the title, an auto-encoder is [a type of neural network](https://en.wikipedia.org/wiki/Autoencoder)
