### ISSUE TITLE
BUG - Programming MCU FW + Resetting UIO Daemon

### ISSUE THREAD

**Issue by Gianco99** [apollo-lhc/cm_mcu#215]
Steps to reproduce the error include:

Install MCU FW and set-up address tables in /fw/CM as described here - https://apollo-lhc.gitlab.io/SM_Firmware/CM_MCU/Installation/

Reboot UIO Daemon to find new MCU address tables as described in the second note here - https://apollo-lhc.gitlab.io/SM_Software/linux-daemons/#daemons

This sequence of commands appears to be successful; however, it brings the Zynq CPU down. A simple reset of the Zynq resolves the issue, and MCU FW registers can be read appropriately.

**Comment by Gianco99** [comment]
Linked to - https://gitlab.com/apollo-lhc/soc-tools/bootup-daemon/-/issues/8

**Comment by pwittich** [comment]
which version of the MCU FW did you install? 
FWIW, I don't think this is a MCU bug, this sounds like a zynq bug?

**Comment by Gianco99** [comment]
This was using - v0.99.6

**Comment by pwittich** [comment]
@Gianco99 can this be closed? I don't think this MCU related.
