### ISSUE TITLE
test clock synthesizer

### ISSUE THREAD

**Issue by pwittich** [apollo-lhc/cm_mcu#28]
We need to test the clock synthesizer chip. Sample code attached. Basic I2C reads and writes have been performed to the chip. 
[Si5340-RevD-Registers_no_amble.h.txt](https://github.com/apollo-lhc/cm_mcu/files/3853229/Si5340-RevD-Registers_no_amble.h.txt)
[Si5340-RevD-Registers.h.txt](https://github.com/apollo-lhc/cm_mcu/files/3853230/Si5340-RevD-Registers.h.txt)

From Charlie:

> I have attached 2 configuration files exactly as they are generated by the SI labs "clock builder" program.
> 
> The difference is that the one named "..._no_amble" does not contain the pre-amble nor post-amble that must be sent to the chip. These missing chunks of settings are always the same, and a 300 milli-second delay is required after sending the pre-amble. You may decide that it would be easier to hard-code these into the MCU program, or you may decide to insert the delay wait after sending the pre-amble.
> 
> [...] I would not manipulate the output file from the clock builder [...]. I would us the file as generated and have my program that sends data to the MCU do the manipulation. [...]
> 
> The manipulation involves determining when the page changes and inserting a write of the new page to address 0x01. The data in the file fills an array of structures. The first data in the structure is a 16-bit address. If the high byte is different than the high byte of the previous address, use the value of the high byte to cause a page change. Always send the register number stored in the low byte of the address along with the corresponding data.
>

**Comment by rzouCERN** [comment]
The programing of the chip is achieved. The tool is in https://github.com/apollo-lhc/mcu_tools/pull/2. Changes to firmware for Kintex & Virtex to enable the transcievers to use this clock source are yet to be merged.
