### ISSUE TITLE
crash in errbuff_out

### ISSUE THREAD

**Issue by pwittich** [apollo-lhc/cm_mcu#50]
https://github.com/apollo-lhc/cm_mcu/blob/c50dedba46139e610cd0c5890607757409799cc9/projects/cm_mcu/CommandLineTask.c#L943-L951

I think there are two issues in this function
1. here you are using a somewhat obscure feature of c called "variable length arrays" that depends on the stack size being big enough. On our little microcontroller it is probably safer to instead create a static array with some size (like 25 entries) and then if the argument asks for more than that limit the output to 25 entries and print an error message 
1. The buffer we write to `m` overruns its boundary when `copied>SCRATCH_SIZE` if you look at e.g. `adc_ctl` we handle this by returning `pdTRUE` when we are close to overrunning the buffer; the CLI tool will keep calling the function until all values have been copied.  The signaling mechanism is the static variable `whichadc` which keeps track of where you are in the output loop.
https://github.com/apollo-lhc/cm_mcu/blob/c50dedba46139e610cd0c5890607757409799cc9/projects/cm_mcu/CommandLineTask.c#L507-L527

can you fix the second issue for sure and also check the other functions if they have this issue? I've been sloppy of not checking this for small functions...

**Comment by gwengardner** [comment]
I've made the two changes to errbuff_out, and pushed the changes to the branch errbuffer_messages. I see that some of the other functions don't all check for `copied>SCRATCH_SIZE`, but it seems that all of those are short enough that they won't cause issues unless we add several lines. Should I go ahead and throw in an if statement anyway?

**Comment by pwittich** [comment]
I guess to be safe that would be prudent, though there are a lot of functions in that file that also should be updated the same way ....

**Comment by pwittich** [comment]
#53 closes this issue
